name: 'Package Upload'
description: 'Uploads a package to Chassy Index'
author: 'Chassy'

inputs:
  name:
    description: 'name of package or image'
    required: true
  path:
    description:
      'fully qualified path to image file or a glob search path for image'
    required: true
  architecture:
    description: 'architecture of image to be uploaded'
    required: true
  os:
    description: 'operating system name for compatibility tracking'
    required: true
  version:
    description: 'operating system version for compatibility tracking'
    required: true
  type:
    description: 'what is the artifact type'
    required: true
  classification:
    description: 'for file and archives, what is the class of artifact'
    required: false
  mode:
    description: 'determine if we should run in debug or standard info mode'
    required: false
  dryrun:
    description: 'determine if we should run in dryrun mode or not'
    required: false
outputs:
  status:
    description: 'A log/status message denoting the success of the upload'
runs:
  using: node20
  main: dist/index.js
