name: 'Package Upload'
description: 'Uploads a package to Chassy Index'
author: 'Chassy'

inputs:
  name:
    description: 'name of package or image'
    required: true
  path:
    description:
      'fully qualified path to image file or a glob search path for image'
    required: true
  architecture:
    description: 'architecture of image to be uploaded'
    required: true
  os:
    description: 'operating system name for compatibility tracking'
    required: true
  os_version:
    description: 'operating system version for compatibility tracking'
    required: true
  version:
    description: 'version of package or image'
    required: false
  type:
    description: 'what is the artifact type'
    required: true
  classification:
    description: 'for file and archives, what is the class of artifact'
    required: false
outputs:
  id:
    description: 'Id of created package or image'
runs:
  using: node20
  main: dist/index.js
